"use client";
import ContentImage from "@/components/ContentImage/ContentImage";
import dynamic from "next/dynamic";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { slugify } from "@/lib/utils";
import styles from "./BlogForm.module.css";
const RichTextEditor = dynamic(() => import("@/components/RichTextEditor/RichTextEditor"), { ssr: false });

const empty = { title: "", slug: "", excerpt: "", content: "<p>Start writing your article…</p>", coverImage: "", imageAlt: "", category: "Engineering", tags: [], featured: false, status: "draft", seo: { title: "", description: "", keywords: [], ogTitle: "", ogDescription: "", ogImage: "" } };
export default function BlogForm({ initial, id }) {
  const router = useRouter(); const [form, setForm] = useState(initial || empty); const [tagInput, setTagInput] = useState((initial?.tags || []).join(", ")); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); const setSeo = (key, value) => setForm((current) => ({ ...current, seo: { ...current.seo, [key]: value } }));
  async function submit(status) { setBusy(true); setMessage(""); const payload = { ...form, status, slug: slugify(form.slug || form.title), tags: tagInput.split(",").map((tag) => tag.trim()).filter(Boolean) }; const response = await fetch(id ? `/api/blogs/${id}` : "/api/blogs", { method: id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) setMessage(data.error || "Unable to save blog."); else { setMessage(status === "published" ? "Blog published successfully." : "Draft saved successfully."); if (!id && data.id) router.replace(`/admin/blogs/${data.id}/edit`); else router.refresh(); } setBusy(false); }
  async function image(event, key = "coverImage") { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 1500000) { setMessage("Use a JPG, PNG, or WebP image under 1.5 MB."); return; } const reader = new FileReader(); reader.onload = () => set(key === "coverImage" ? key : "seo", key === "coverImage" ? reader.result : { ...form.seo, ogImage: reader.result }); reader.readAsDataURL(file); }
  return <div className={styles.form}><section><label>Title<input required value={form.title} onChange={(e) => { set("title", e.target.value); if (!id) set("slug", slugify(e.target.value)); }} placeholder="A clear, useful article title" /></label><label>Slug<input value={form.slug} onChange={(e) => set("slug", slugify(e.target.value))} /></label><label>Excerpt<textarea required rows="3" value={form.excerpt} onChange={(e) => set("excerpt", e.target.value)} maxLength="320" placeholder="A concise summary for cards and search results" /></label></section><section><h2>Content</h2><RichTextEditor value={form.content} onChange={(value) => set("content", value)} /></section><div className={styles.columns}><section><h2>Organization</h2><label>Category<input value={form.category} onChange={(e) => set("category", e.target.value)} /></label><label>Tags<input value={tagInput} onChange={(e) => setTagInput(e.target.value)} placeholder="React, JavaScript" /></label><label className={styles.check}><input type="checkbox" checked={form.featured} onChange={(e) => set("featured", e.target.checked)} /> Featured article</label></section><section><h2>Cover image</h2><label className={styles.upload}>Upload JPG, PNG, or WebP under 1.5 MB<input type="file" accept="image/jpeg,image/png,image/webp" onChange={image} /></label><label>Cover image description<input value={form.imageAlt || ""} onChange={(e) => set("imageAlt", e.target.value)} maxLength="250" placeholder="Describe the image for readers who cannot see it" /></label>{form.coverImage && <ContentImage className={styles.preview} src={form.coverImage} alt="Cover preview" />}</section></div><section><h2>SEO</h2><div className={styles.columns}><label>SEO title<input value={form.seo.title} onChange={(e) => setSeo("title", e.target.value)} maxLength="180" /></label><label>Meta description<textarea value={form.seo.description} onChange={(e) => setSeo("description", e.target.value)} maxLength="320" /></label><label>Social preview title<input value={form.seo.ogTitle || ""} onChange={(e) => setSeo("ogTitle", e.target.value)} maxLength="180" /></label><label>Social preview description<textarea value={form.seo.ogDescription || ""} onChange={(e) => setSeo("ogDescription", e.target.value)} maxLength="320" /></label><label>Custom social image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => image(event, "ogImage")} />{form.seo.ogImage && <span>Custom image selected. <button type="button" onClick={() => setSeo("ogImage", "")}>Use cover image instead</button></span>}</label></div></section>{message && <p className={styles.message}>{message}</p>}<div className={styles.actions}><button className="btn btnOutline" type="button" disabled={busy} onClick={() => submit("draft")}>Save draft</button><button className="btn btnPrimary" type="button" disabled={busy} onClick={() => submit("published")}>{busy ? "Saving…" : "Publish"}</button></div></div>;
}
